taxi/urls.py
from django.urls import path

from .views import (
    index,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView,
    ManufacturerListView,
    CarCreateView,
    CarUpdateView,
    CarUpdateView,
    CarDeleteView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    DriverCreateView,
    DriverLicenseUpdateView,
    DriverDeleteView,
    manipulation_with_car,
)

urlpatterns = [
    path("", index, name="index"),
    path("manufacturers/", ManufacturerListView.as_view(), name="manufacturer-list"),
    path(
        "manufacturers/create",
        ManufacturerCreateView.as_view(),
        name="manufacturer-create",
    ),
    path(
        "manufacturers/<int:pk>/update",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update",
    ),
    path(
        "manufacturers/<int:pk>/delete/",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete",
    ),
    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("cars/create/", CarCreateView.as_view(), name="car-create"),
    path("cars/<int:pk>/update/", CarUpdateView.as_view(), name="car-update"),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),
    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
    path("drivers/<int:pk>/delete/", DriverDeleteView.as_view(), name="driver-delete"),
    path("drivers/create/", DriverCreateView.as_view(), name="driver-create"),
    path(
        "drivers/<int:pk>/license_number/",
        DriverLicenseUpdateView.as_view(),
        name="license-number-update",
    ),
    path(
        "drivers/<int:pk>/change_car/",
        manipulation_with_car,
        name="manipulation_with_car",
    ),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.country})"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"
        ordering = ["id"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={"pk": self.pk})


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    def __str__(self):
        return self.model

taxi/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from taxi.models import Driver, Car


class DriverCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Driver
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "license_number",
        )

    def clean_license_number(self):
        license_number = self.cleaned_data["license_number"]
        return check_license_number(license_number)


class CarForm(forms.ModelForm):
    drivers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Car
        fields = "__all__"


class DriverLicenseUpdateForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ("license_number",)

    def clean_license_number(self):
        license_number = self.cleaned_data["license_number"]
        return check_license_number(license_number)


def check_license_number(number):
    if len(number) != 8:
        raise ValidationError("License must have 8 characters.")
    if not number[:3].isalpha():
        raise ValidationError("First 3 characters must be letters.")
    if not number[:3].isupper():
        raise ValidationError("First 3 characters must be upper letters.")
    if not number[3:].isdigit():
        raise ValidationError("Last 5 characters must be numbers.")
    return number


class DriverSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by last name..."}),
    )

taxi/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import (
    DriverCreationForm,
    DriverLicenseUpdateForm,
    CarForm,
    DriverSearchForm,
)
from .models import Driver, Car, Manufacturer


@login_required
def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits + 1,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(LoginRequiredMixin, generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "taxi/manufacturer_list.html"
    paginate_by = 5


class ManufacturerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Manufacturer
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_confirm_delete.html"


class CarListView(LoginRequiredMixin, generic.ListView):
    model = Car
    paginate_by = 5
    queryset = Car.objects.all().select_related("manufacturer")


class CarDetailView(LoginRequiredMixin, generic.DetailView):
    model = Car


class CarCreateView(LoginRequiredMixin, generic.CreateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Car
    template_name = "taxi/car_confirm_delete.html"
    success_url = reverse_lazy("taxi:car-list")


class DriverListView(LoginRequiredMixin, generic.ListView):
    model = Driver
    paginate_by = 5
    queryset = Driver.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DriverListView, self).get_context_data(**kwargs)

        last_name = self.request.GET.get("last_name", "")

        context["search_form"] = DriverSearchForm(initial={"last_name": last_name})

        return context

    def get_queryset(self):
        form = DriverSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                last_name__icontains=form.cleaned_data["last_name"]
            )

        return self.queryset


class DriverDetailView(LoginRequiredMixin, generic.DetailView):
    model = Driver
    queryset = Driver.objects.all().prefetch_related("cars__manufacturer")


class DriverCreateView(LoginRequiredMixin, generic.CreateView):
    model = Driver
    form_class = DriverCreationForm


class DriverLicenseUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = DriverLicenseUpdateForm
    template_name = "taxi/driver_license_update_page.html"


class DriverDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Driver
    template_name = "taxi/driver_confirm_delete.html"
    success_url = reverse_lazy("taxi:driver-list")


def manipulation_with_car(request, pk):
    driver = Driver.objects.get(id=request.user.id)
    if Car.objects.get(id=pk) in driver.cars.all():
        driver.cars.remove(pk)
    else:
        driver.cars.add(pk)

    return HttpResponseRedirect(reverse_lazy("taxi:car-detail", args=[pk]))

templates/taxi/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Delete Car</h1>

    <p>Are you sure you want to delete the car: {{ car.model }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">

    </form>

{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block content %}
    <span style="float: right">
        {% if user in car.drivers.all %}
            <p>You are a driver of this car! <a class="btn btn-danger"
                                                  href="{% url 'taxi:manipulation_with_car' pk=car.pk %}">Delete me from this car</a></p>
        {% else %}
            <p>You are not a driver of this car! <a class="btn btn-success"
                                                      href="{% url 'taxi:manipulation_with_car' pk=car.pk %}">Assign me to this car</a></p>
        {% endif %}
    </span>
    <h1>Model: {{ car.model }}</h1>

    <p>Manufacturer: ({{ car.manufacturer.name }}, {{ car.manufacturer.country }})</p>

    <h1>Drivers</h1>
    <hr>
    <ul>
        {% for driver in car.drivers.all %}
            <li>{{ driver.username }} ({{ driver.first_name }} {{ driver.last_name }})</li>
        {% endfor %}
    </ul>
    <hr>

    <a class="btn btn-info" href="{% url 'taxi:car-update' pk=car.id %}">Update</a>
    <a class="btn btn-danger" href="{% url 'taxi:car-delete' pk=car.id %}">Delete</a>
{% endblock %}

templates/taxi/car_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} Car</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Car list
        <a style="float: right" class="btn btn-success" href="{% url 'taxi:car-create' %}">Create new car</a>
    </h1>
    {% if car_list %}
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Model</th>
                <th>Manufacturer</th>
                <th>Country</th>
            </tr>

            {% for car in car_list %}
                <tr>
                    <td>
                        {{ car.id }}
                    </td>
                    <td>
                        <a href="{% url "taxi:car-detail" pk=car.id %} ">{{ car.model }}</a>
                    </td>
                    <td>
                        {{ car.manufacturer.name }}
                    </td>
                    <td>
                        {{ car.manufacturer.country }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no cars in taxi</p>
    {% endif %}
{% endblock %}

templates/taxi/driver_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Delete Driver</h1>

    <p>Are you sure you want to delete the driver:
        <strong>{{ driver.first_name }} {{ driver.last_name }} ({{ driver.username }})?</strong></p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">

    </form>

{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Username: {{ driver.username }}
    </h1>

    <p><strong>First name:</strong> {{ driver.first_name }}</p>
    <p><strong>Last name:</strong> {{ driver.last_name }}</p>
    <p><strong>License number:</strong> {{ driver.license_number }} <a class="btn-sm btn-info"
                                                                       href="{% url "taxi:license-number-update" pk=driver.pk %}">Update</a>
    </p>
    <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

    <div class="ml-3">
        <h4>Cars</h4>

        {% for car in driver.cars.all %}
            <hr>
            <p><strong>Model:</strong> {{ car.model }}</p>
            <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ car.id }}</p>

        {% empty %}
            <p>No cars!</p>
        {% endfor %}

        <a class="btn btn-danger" href="{% url 'taxi:driver-delete' pk=driver.pk %}">Delete driver</a>
    </div>
{% endblock %}

templates/taxi/driver_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} Driver</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/driver_license_update_page.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>Update License Number</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
        Driver List
        <a style="float: right" class="btn btn-success" href="{% url 'taxi:driver-create' %}">Create new driver</a>
    </h1>

    <form action="" method="get" class="form-inline">
        {{ search_form|crispy }}
        <input class="btn btn-info" type="submit" value="Search">
    </form>

    {% if driver_list %}
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>First name</th>
                <th>Last name</th>
                <th>License number</th>
            </tr>
            {% for driver in driver_list %}
                <tr>
                    <td>{{ driver.id }}</td>
                    <td><a href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %}
                        (Me){% endif %}</a></td>
                    <td>{{ driver.first_name }}</td>
                    <td>{{ driver.last_name }}</td>
                    <td>{{ driver.license_number }}</td>
                </tr>
            {% endfor %}

        </table>
    {% else %}
        <p>There are no drivers in the service.</p>
    {% endif %}
{% endblock %}

templates/taxi/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Taxi Service Home</h1>
    <p>Welcome to Best Taxi Ever!</p>
    <h2>Dynamic content</h2>
    <p>The Taxi service has the following record counts:</p>
    <ul>
        <li><strong>Cars:</strong> {{ num_cars }}</li>
        <li><strong>Drivers:</strong> {{ num_drivers }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/taxi/manufacturer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <h1>Delete Manufacturer</h1>

    <p>Are you sure you want to delete the manufacturer: {{ manufacturer.name }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">

    </form>

{% endblock %}

templates/taxi/manufacturer_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} Manufacturer</h1>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Manufacturer List
        <a style="float: right" class="btn btn-success" href="{% url 'taxi:manufacturer-create' %}">Create new manufacturer</a>
    </h1>

    {% if manufacturer_list %}
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Country</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>

            {% for manufacturer in manufacturer_list %}
                <tr>
                    <td>
                        {{ manufacturer.id }}
                    </td>
                    <td>
                        {{ manufacturer.name }}
                    </td>
                    <td>
                        {{ manufacturer.country }}
                    </td>
                    <td>
                        <a href="{% url "taxi:manufacturer-update" pk=manufacturer.pk %}">Update</a>
                    </td>
                    <td>
                        <a class="text-danger" href="{% url "taxi:manufacturer-delete" pk=manufacturer.pk %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

    {% else %}
        <p>There are no manufacturers in the service.</p>
    {% endif %}
{% endblock %}